/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import org.junit.Test;

import src.controller.PointOfSaleController;

import static org.junit.Assert.*;

public class PointOfSaleControllerTest {
    @Test public void appHasAGreeting() {
        PointOfSaleController classUnderTest = new PointOfSaleController();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
